name: Run Gradle on Pushes on Main an Pull Requests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle assemble
        run: ./gradlew assemble --scan

      - name: Execute Gradle check
        run: ./gradlew check --scan

      - name: Execute Gradle sonarqube
        run: ./gradlew sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }} --scan
